server:
  servlet:
    context-path: /api/client/v1/
  port: 8080

spring:
  application:
    name: client

  datasource:
    url: jdbc:postgresql://localhost:5432/client_db
    username: client_db_user
    password: client_db_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

client-api:
  jwt-secret: iPZpVgpwfAyyiaSv
  encrypt-strength: 5
